Repository IBM/ibm-catalog-ui-operator, pull requests merged in 2020-03, with the labels that each got.

#5 refactor catalog-ui operator
  .osdk-scorecard.yaml
  Makefile
  README.md
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  commonUtil/resources/opencloud-operators.yaml
  commonUtil/scripts/generate-scorecard.sh
  commonUtil/scripts/push-csv.sh
  deploy/crds/charts.helm.k8s.io_v1alpha1_icpcatalogchart_cr.yaml
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/ibm-catalog-ui-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  helm-charts/icp-catalog-chart/Chart.yaml
  helm-charts/icp-catalog-chart/README.md
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/templates/rbac.yaml
  helm-charts/icp-catalog-chart/values.yaml
  watches.yaml
Labels: approved, lgtm, size/XL

#6 fix catalog vascan vulnerability issue
  build/Dockerfile
  build/Dockerfile.ppc64le
Labels: approved, lgtm, size/XS

#7 bump up icp-catalog-ui operand image to 3.2.4
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/ibm-catalog-ui-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/S

#8 fix cluster port to use 443 instead 8443
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/ibm-catalog-ui-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/icp-catalog-chart/README.md
  helm-charts/icp-catalog-chart/templates/NOTES.txt
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/S

#10 add labels and license to docker files to pass image scan
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/M

#11 update healthcheck dependencies annotation
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
Labels: approved, lgtm, size/XS

#12 add version to CRD
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/operator.ibm.com_cataloguis_crd.yaml
Labels: approved, lgtm, size/XS

#13 add dev-image target to Makefile
  Makefile
Labels: approved, lgtm, size/S

#14 update csv metadata fields
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#15 clean up for RH certification
  Makefile
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#16 fixed wrong containerImage annotation
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#17 add README.md
  README.md
  SECURITY_CONTACTS
Labels: approved, lgtm, size/M
