Repository IBM/ibm-catalog-ui-operator, pull requests merged in 2020-09, with the labels that each got.

#68 fix linting errors
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/ibm-catalog-ui-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/0.0.1/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
Labels: approved, lgtm, size/L

#69 40607: reduce operator cpu request and limit
  Makefile
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.3/ibm-catalog-ui-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
Labels: approved, lgtm, size/S

#70 update operand image digest
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.3/ibm-catalog-ui-operator.v3.6.3.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/XS

#71 updated csv to v3.6.4
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.4/ibm-catalog-ui-operator.v3.6.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.4/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/icp-catalog-chart/Chart.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/L
