Repository IBM/ibm-catalog-ui-operator, pull requests merged in 2020-05, with the labels that each got.

#36 37259: changes to address restricted scc
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/icp-catalog-chart/templates/catalog-service.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/templates/ingress.yaml
  helm-charts/icp-catalog-chart/templates/rbac.yaml
  helm-charts/icp-catalog-chart/values-metadata.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/L

#37 37644: revert crd back to v1alpha1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#38 update readme and csv description
  README.md
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#39 support 3.2.4 to 3.4 upgrade path
  Makefile
  README.md
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/values-metadata.yaml
  helm-charts/icp-catalog-chart/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#40 37887: Canary Failure: Catalog-UI operator will not install
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/values-metadata.yaml
  helm-charts/icp-catalog-chart/values.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#41 Cleanup
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/S

#42 37376: Update Helm foundation operators description and documentation
  README.md
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#43 37933: Helm foundation: Update productVersion metering annotations to…
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
Labels: approved, lgtm, size/XS

#44 update icp-catalog-ui operand image digest
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/S

#45 update instance labels to match operand, update manifest digest versions
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/S

#46 increase operator resources to avoid OOM
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#47 38052: Creating beta channel for cloud pak usage
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#48 second cleanup
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/M

#49 bump up csv to 3.6.1
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/bump-up-csv.sh
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.1/ibm-catalog-ui-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.1/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/Chart.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/XL

#50 add protect-csv githook
  .githooks/pre-commit
  Makefile
  commonUtil/scripts/protect-csv.sh
  commonUtil/scripts/push-csv.sh
Labels: approved, lgtm, size/M

#51 update README
  README.md
  commonUtil/scripts/protect-csv.sh
Labels: approved, lgtm, size/XS

#52 update icp-catalog-ui operand image
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.1/ibm-catalog-ui-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/S

#53 update digest in manifest.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/XS

#54 retrigger quay failed job
  OWNERS
Labels: approved, lgtm, size/XS

#55 38341: Helm Foundation - Move CS 3.4.1 into beta channel
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.1/ibm-catalog-ui-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
