Repository IBM/ibm-catalog-ui-operator, pull requests merged in 2020-08, with the labels that each got.

#58 40023 - integrate with new CICD pipeline
  Makefile
  commonUtil/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#59 40023 - downgrade manifest-tool to v0.7.0
  Makefile
Labels: approved, lgtm, size/XS

#60 improve dev workflow
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.2/ibm-catalog-ui-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/M

#61 removed productVersion annotation
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.2/ibm-catalog-ui-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
Labels: approved, lgtm, size/XS

#62 update images
  build/Dockerfile.s390x
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/XS

#63 40210: add pod anit-affinity for HA support
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
Labels: approved, lgtm, size/S

#64 updated CSV to v3.6.3
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.3/ibm-catalog-ui-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.3/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  helm-charts/icp-catalog-chart/Chart.yaml
Labels: approved, lgtm, size/XL

#65 added multi-arch support labels
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.3/ibm-catalog-ui-operator.v3.6.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#67 40594: Canary Failure: helm-repo and catalog-ui not running on OCP 4.6
  helm-charts/icp-catalog-chart/Chart.yaml
Labels: approved, lgtm, size/XS
