Repository IBM/ibm-catalog-ui-operator, pull requests merged in 2020-04, with the labels that each got.

#19 specify amd64 operator image for bundle to pass RH certification
  .gitignore
  Makefile
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#21 undo amd64 tagging
  deploy/olm-catalog/ibm-catalog-ui-operator/3.5.0/ibm-catalog-ui-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#22 update version to 3.5.0
  helm-charts/icp-catalog-chart/Chart.yaml
Labels: approved, lgtm, size/XS

#18 flesh out validation definintion
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
Labels: approved, lgtm, size/M

#23 3.5.0->3.6.0
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#24 update 3.6.0 csv and crd
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
Labels: approved, lgtm, size/M

#26 37142: add imageRegistry for CICD
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  helm-charts/icp-catalog-chart/Chart.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/M

#27 36969: add operator dependencies
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#28 add dev channel
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
Labels: approved, lgtm, size/XS

#29 37228: remove unnecessarily exposed configurations
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/ibm-catalog-ui-operator.package.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#30 fixes to prepare for integration build
  Makefile
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#32 fix broken catalog-ui operator
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#33 37464: Remediate package vulnerability
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#34 use image digest instead of tags
  deploy/crds/operator.ibm.com_cataloguis_crd.yaml
  deploy/crds/operator.ibm.com_v1_catalogui_cr.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/ibm-catalog-ui-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-catalog-ui-operator/3.6.0/operator.ibm.com_cataloguis_crd.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/manifest.yaml
  helm-charts/icp-catalog-chart/ibm_cloud_pak/qualification.yaml
  helm-charts/icp-catalog-chart/templates/catalog-ui.yaml
  helm-charts/icp-catalog-chart/values.yaml
Labels: approved, lgtm, size/M
